### PR TITLE
feat: add error messages to error flashes

### LINKED ISSUE #128: Display specific error message in error flash
### Is your feature request related to a problem?

The specific error message is not shown in the error flashes.

### Describe the solution you'd like

The error message generated by the api request should be returned and added to the error flashes.

### Describe alternatives you've considered

_No response_

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by sutterj**
# Pull Request

## Proposed Changes

- Closes #128 
  - Add error messages to error flashes
  - Display error messages if error when creating, editing, and deleting mirrors

### Author/Contributor

- [ ] If documentation is needed for this change, has that been included in this pull request
- [X] run `npm run lint` and fix any linting issues that have been introduced
- [X] run `npm run test` and run tests
- [ ] If publishing new data to the public (scorecards, security scan results, code quality results, live dashboards, etc.), please request review from `@jeffrey-luszcz`

### Reviewer

- [X] Label as either `bug`, `documentation`, `enhancement`, `infrastructure`, `maintenance`, or `breaking`

### CODE REVIEW

**Comment by sutterj** [comment]
Currently there is some handling in the create procedure to make a "pretty" message if one already exists:

Image

This is the only error that has this, so is it worthwhile to do this for the other procedures or is that too specific/tedious because of the number of possible errors:

Image

**Comment by zkoppert** [comment]
> Currently there is some handling in the create procedure to make a "pretty" message if one already exists:
> 
> Image
> 
> This is the only error that has this, so is it worthwhile to do this for the other procedures or is that too specific/tedious because of the number of possible errors:
> 
> Image

@ahpook thoughts?

**Review by ajhenry — APPROVED** [review]
looks good from an engineering pov

**Comment by ahpook** [comment]
Hmmm. How many potential other messages are we looking at? The json barf is pretty ugly ... 

Is the format predictable enough to extract the `message` field and pretty-print that with a generic "Failed to create mirror. Error was: <message>" banner?

**Comment by sutterj** [comment]
I'm not really sure how many, but I would guess that the name conflict one is probably the most common and that one is already covered.  I would imagine that the API is consistent and returns a message field though and that would be easy to add to the banner by itself.

**Pull request merged**
